[package]
name = "easy_ast_resolver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oxc_resolver = "0.2.0"
easy_ast_error = { version = "0.1.0", path = "../error" }
regex = "1.10.2"